version: '3'
services:
  vue-app:
    build:
      context:
        dockerfile: Dockerfile
      ports:
        - '3000:80'
        - '5173:5173'
      volumes:
        - ./src:/app/src
        - ./public:/app/public
        - node_modules:/app/node_modules
      environment:
        - NODE_ENV=development
        - VITE_API_URL=http://localhost:3000
      restart: unless-stopped

volumes:
  node_modules:
