services:
  vue-app:
    build: .
    ports:
      - '3000:80'
      - '5173:5173'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
